# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run generate
      - uses: milanmk/actions-file-deployer@master
        with:
            remote-host: ${{ secrets.DEPLOY_HOST }}
            remote-user: ${{ secrets.DEPLOY_USER }}
            remote-password: ${{ secrets.DEPLOY_PASSWORD }}
            remote-port: ${{ secrets.DEPLOY_PORT }}
            remote-path: "/www"
            local-path: "./dist/"
            sync: 'full'

